---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    driver:
      vm_hostname: 'test'
    run_list:
      - recipe[opsline-hostname::default]
    attributes:
      opsline-hostname:
        domain: 'example.com'
  - name: no-fqdn
    run_list:
      - recipe[opsline-hostname::default]
    attributes:
      opsline-hostname:
        domain: 'example.com'
        use_fqdn: false
  - name: localhost
    run_list:
      - recipe[opsline-hostname::default]
    attributes:
      opsline-hostname:
        domain: 'example.com'
        use_localhost_ip: true